pipeline {
    agent any
    environment {
        PATH = "${PATH}:${getTerraformPath()}"
    }
    stages{
        stage('terraform init'){
            steps {
                 sh '''
                  cd STACK-EC2-TF
                  terraform init
                  '''                 
            }
        }

        stage('terraform plan'){
            steps {
                 sh '''
                  cd STACK-EC2-TF
                  terraform plan -out=tfplan -input=false
                  '''                 
            }
        }
    
    }
}
  
def getTerraformPath(){
        def tfHome= tool name: 'Terraform-155', type: 'terraform'
        return tfHome
    }